[package]
name = "curvo"
version = "0.1.8"
authors = ["Masatatsu Nakamura <masatatsu.nakamura@gmail.com"]
edition = "2021"
keywords = ["nurbs", "modeling", "graphics", "3d"]
categories = ["graphics", "modeling"]
description = "NURBS modeling library"
homepage = "https://github.com/mattatz/curvo"
repository = "https://github.com/mattatz/curvo"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.81"
nalgebra = { version = "0.32.5", features = [
  "serde-serialize",
  "convert-glam025",
] }
num-traits = "0.2.18"
rand = "0.8.5"
bevy = { version = "0.13.2", optional = true }
bevy-inspector-egui = { version = "0.24.0", optional = true }
bevy_infinite_grid = { version = "0.12", optional = true }
bevy_normal_material = { version = "0.5.2", optional = true }
bevy_panorbit_camera = { version = "0.17.0", optional = true }
bevy_points = { version = "0.5.1", optional = true }
simba = { version = "0.8.1", default-features = false }

[dev-dependencies]
approx = { version = "0.5", default-features = false }

[features]
default = []
# default = ["bevy"] # for debugging example
bevy = [
  "dep:bevy",
  "dep:bevy-inspector-egui",
  "dep:bevy_infinite_grid",
  "dep:bevy_normal_material",
  "dep:bevy_panorbit_camera",
  "dep:bevy_points"
]

[[example]]
name = "interpolate_curve"
path = "examples/interpolate_curve.rs"
required-features = ["bevy"]

[[example]]
name = "trim_curve"
path = "examples/trim_curve.rs"
required-features = ["bevy"]

[[example]]
name = "loft_surface"
path = "examples/loft_surface.rs"
required-features = ["bevy"]

[[example]]
name = "sweep_surface"
path = "examples/sweep_surface.rs"
required-features = ["bevy"]

[[example]]
name = "revolve_surface"
path = "examples/revolve_surface.rs"
required-features = ["bevy"]

[[example]]
name = "frenet_frame"
path = "examples/frenet_frame.rs"
required-features = ["bevy"]

